export const BookData = [
    {
        id:0,
        book_name: "A Tale of Shipwreck, Mutiny and Murder",
        book_description: "The Wager: A Tale of Shipwreck, Mutiny and Murder is the fifth nonfiction book by American journalist David Grann. The book focuses on the Wager Mutiny. It was published on April",
        book_url: "https://i.ebayimg.com/images/g/gdIAAOSwqn9kPxd9/s-l1600.jpg",
        print_length:"345 pages",
        language: "English",
        author_name: "David Grann",
        price:"1000",
    },
    {
        id:1,
        book_name: "Spare",
        book_description: "Spare is a memoir by Prince Harry, Duke of Sussex, which was released on 10 January 2023. It was ghostwritten by J. R. Moehringer and published by Penguin Random House. It is 416 pages long and available in digital, paperback, and hardcover formats and has been translated into fifteen languages.",
        book_url: "https://upload.wikimedia.org/wikipedia/en/6/69/Spare_cover.jpg",
        print_length:"409 pages",
        language: "English",
        author_name: "Prince Harry, Duke of Sussex",
        price:"8950",
    },
    {
        id:2,
        book_name: "Yellowface",
        book_description: " Yellowface is a 2023 novel written by R. F. Kuang. The book was described as a satire of racial diversity in the publishing industry as well as a metafiction about social media, particularly Twitter. Yellowface is Kuang's first venture into literary fiction.",
        book_url: "https://images.squarespace-cdn.com/content/v1/62e6911b53cc8f67eefc5fa6/1689170796288-TRUHM1IP04M00KXQQT9Z/Kuang_Website.png",
        print_length:"336 pages",
        language: "English",
        author_name: "R.F. Kuang",
        price:"3290",
    },
    {
        id:3,
        book_name: "YPoverty, by America",
        book_description: " Poverty, by America is a 2023 non-fiction book by Matthew Desmond, a sociology professor. Published by Crown Publishing Group, it was released on March 21, 2023.",
        book_url: "https://images-na.ssl-images-amazon.com/images/I/6158gmN0PpL._AC_UL210_SR210,210_.jpg",
        print_length:"304 pages",
        language: "English",
        author_name: "Matthew Desmond",
        price:"1500",
    },
    {
        id:4,
        book_name: "The Covenant of Water",
        book_description: "The Covenant of Water is a 2023 novel by physician and author Abraham Verghese. The book was published by Grove Atlantic. The novel tells the story of an Indian family living in southwest India, in the Kerala state, with the narrative spanning three generations, from 1900 to the 1970s.",
        book_url: "https://images-na.ssl-images-amazon.com/images/I/91b7tm523VL._AC_UL210_SR210,210_.jpg",
        print_length:"736 pages",
        language: "English",
        author_name: "Abraham Verghese",
        price:"3000",
    },
    {
        id:5,
        book_name: "Pineapple Street: A Novel",
        book_description: "A deliciously funny, sharply observed novel of family, wealth, love and tennis, this zeitgeisty debut follows three women in an old Brooklyn Heights clan: one who was born with money, one who married into it, and one, the millennial conscience of the family, who wants to give it all away.",
        book_url: "https://m.media-amazon.com/images/I/91C27J+LgbL._AC_UF1000,1000_QL80_.jpg",
        print_length:"303 pages",
        language: "English",
        author_name: "Jenny Jackson",
        price:"7000",
    }

]